#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo Start tests
dotnet test D:/Codingapps/BinaryToJSONConverterApp/ServerConnectionTests/ServerConnectionTests.csproj
dotnet test D:/Codingapps/BinaryToJSONConverterApp/JsonBinLibTests/JsonBinLibTests.csproj
echo Start format
npx lint-staged --relative
